// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6cWzuinBBXRaXAv_0Lt6XAGfk0tWxHUU',
    appId: '1:821343051128:web:0872cebb13ffaf4e7a7c8d',
    messagingSenderId: '821343051128',
    projectId: 'hotelreservation-1d166',
    authDomain: 'hotelreservation-1d166.firebaseapp.com',
    databaseURL: 'https://hotelreservation-1d166-default-rtdb.firebaseio.com',
    storageBucket: 'hotelreservation-1d166.appspot.com',
    measurementId: 'G-CC3BCBSVTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZBkgXfpAKnEijCA66nWq82ig1kILg9vQ',
    appId: '1:821343051128:android:7c39c60450163a197a7c8d',
    messagingSenderId: '821343051128',
    projectId: 'hotelreservation-1d166',
    databaseURL: 'https://hotelreservation-1d166-default-rtdb.firebaseio.com',
    storageBucket: 'hotelreservation-1d166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWmK-j_d760TPLVdPQTWazt_PTMuG54yM',
    appId: '1:821343051128:ios:b53907d5e5fffdc07a7c8d',
    messagingSenderId: '821343051128',
    projectId: 'hotelreservation-1d166',
    databaseURL: 'https://hotelreservation-1d166-default-rtdb.firebaseio.com',
    storageBucket: 'hotelreservation-1d166.appspot.com',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWmK-j_d760TPLVdPQTWazt_PTMuG54yM',
    appId: '1:821343051128:ios:b53907d5e5fffdc07a7c8d',
    messagingSenderId: '821343051128',
    projectId: 'hotelreservation-1d166',
    databaseURL: 'https://hotelreservation-1d166-default-rtdb.firebaseio.com',
    storageBucket: 'hotelreservation-1d166.appspot.com',
    iosBundleId: 'com.example.flutterProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6cWzuinBBXRaXAv_0Lt6XAGfk0tWxHUU',
    appId: '1:821343051128:web:b040fe32d66276947a7c8d',
    messagingSenderId: '821343051128',
    projectId: 'hotelreservation-1d166',
    authDomain: 'hotelreservation-1d166.firebaseapp.com',
    databaseURL: 'https://hotelreservation-1d166-default-rtdb.firebaseio.com',
    storageBucket: 'hotelreservation-1d166.appspot.com',
    measurementId: 'G-EC8LJ7YM82',
  );

}